# Generated by Django 4.1.7 on 2023-03-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=3)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('population', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Powerplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=3)),
                ('capacity_mw', models.DecimalField(decimal_places=2, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('primary_fuel', models.CharField(max_length=50)),
                ('other_fuel1', models.CharField(max_length=50)),
                ('other_fuel2', models.CharField(max_length=50)),
                ('other_fuel3', models.CharField(max_length=50)),
                ('renewable', models.IntegerField()),
            ],
        ),
    ]
