# Generated by Django 4.1.6 on 2023-03-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temperature_f', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind_kph', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind_mph', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStationMonthlyAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=3)),
                ('temperature_f', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind_kph', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind_mph', models.DecimalField(decimal_places=1, max_digits=4)),
                ('number_of_sunny_days', models.IntegerField()),
                ('number_of_windy_days', models.IntegerField()),
            ],
        ),
    ]
