# Generated by Django 4.1.6 on 2023-04-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeatherMonthlyAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('temperature_c_avg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('temperature_c_min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('temperature_c_max', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind_kph', models.DecimalField(decimal_places=1, max_digits=4)),
                ('number_of_sunny_days', models.IntegerField()),
            ],
        ),
    ]
