# Generated by Django 4.1.7 on 2023-04-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_cityweathermonthlyaverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityWeatherYearlyAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('temperature_c_avg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('temperature_c_min', models.DecimalField(decimal_places=1, max_digits=4)),
                ('temperature_c_max', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wind_kph', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='CityWeatherMonthlyAverage',
        ),
    ]
