# Generated by Django 4.1.7 on 2023-03-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_powerplants_powerplant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powerplant',
            old_name='powerplant_name',
            new_name='name',
        ),
    ]
