# Generated by Django 4.1.7 on 2023-03-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.CharField(max_length=9),
        ),
    ]
