# Generated by Django 4.1.7 on 2023-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_city_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='powerplant',
            name='country',
            field=models.CharField(max_length=3),
        ),
    ]
